'\" t
.TH ted 1  "June 18, 2017" "version 0.1" "MYPROGRAMM"
.SH NAME
ted \- console text editor
.SH SYNOPSIS
ted
[file]
.SH DESCRIPTION
Created based on the console part of the editor sam.
Educational material. Not a standard approach was used. In general, the buzz.
.SH OPTIONS
There are no options, backwater and drove.
Takes only one optional parameter - the name of the file being edited.
.SH EXAMPLES
.TP
ted myfile.txt
.TP
ted
.SH EXIT STATUS
ted returns a zero exist status if it succeeds. Non zero is returned in case of failure.
.SH AUTHOR
nezabudka gxendz@mail.ru
.SH SEE ALSO
sam(in plan9)
